import { HStack } from "@chakra-ui/react";
import Head from "next/head";

export const AuthLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HStack position="absolute" width="full" height="100vh" maxW="full" justifyContent="center" alignItems="center">
        {children}
      </HStack>
    </>
  );
};
