import { VStack } from "@chakra-ui/react";
import { Navbar } from "components/layout/navbar";
import Head from "next/head";
import Footer from "./footer";

const MainLayout: React.FC<React.PropsWithChildren<{ title: string }>> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " | Ahmad Gani" : "Ahmad Gani"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack alignItems={"stretch"} as={"main"} spacing={5}>
        <Navbar />
        {children}
        <Footer />
      </VStack>
    </>
  );
};

export default MainLayout;
