import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as={"main"} display={"flex"} justifyContent={"center"} alignItems={"center"} w={"100vw"} h={"100vw"} bg={"whiteAlpha.100"}>
        <p>Hello World</p>
      </Box>
    </>
  );
}
